config/routes.rb
OstazIii::Application.routes.draw do
  
  
  root 'transactions#index'
  devise_for :users
  resources :transactions
  resources :accounts
  resources :account_types

end

app/controllers/account_types_controller.rb
class AccountTypesController < ApplicationController
  def index
  	@accounttype = AccountType.all
  end

  def show
  	@accounttype = AccountType.find(params[:id])
  	@accounts = Account.all
  end

  def create
    @accounttype = AccountType.new
    @accounttype.name = params[:account_type][:name]
    respond_to do |format|
      if @accounttype.valid?
        @accounttype.save
        format.html { redirect_to @accounttype, notice: 'Account Type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @accounttype }
      else
        format.html { render action: 'new' }
        format.json { render json: @accounttype.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @accounttype = AccountType.new()
  end

  def destroy
    @found = false
    @accounttype = AccountType.find(params[:id])
    @accounts = Account.all
    @accounts.each do |account|
      if account.account_type_id == @accounttype.id
        @found = true
      end
    end
    if @found == false
      @accounttype.destroy
      respond_to do |format|
        
        format.html{ redirect_to account_types_url}    
        format.json{ head :no_content}
      end
    end
  end

end

app/helpers/account_types_helper.rb
module AccountTypesHelper
end

app/views/account_types/create.html.erb
<h1>AccountTypes#create</h1>
<p>Find me in app/views/account_types/create.html.erb</p>

app/views/account_types/index.html.erb
<h1>AccountTypes Listing</h1>
<table>
<thead>
	<td>Account Name</td>
	<td></td>

</thead>
<tbody>
	<% @accounttype.each do |type| %>
	<tr>
		<td><%= link_to "#{type.name}", account_type_path(type)  %></td>
		<td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
	<% end %>
</tbody>
</table>

app/views/account_types/new.html.erb
<h1>Creating a new Account Type</h1>
<h3> Please enter the name of the new Account Type you would like to add </h3>
<%= form_for(@accounttype) do |f| %>
<% if @accounttype.errors.empty? == false%>
<div id="error_explanation">
  <h2><%= pluralize(@accounttype.errors.count, "error") %> prohibited this account type from being saved:</h2>

  <ul>
    <% @accounttype.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name%>
  <%= f.submit %>


<% end %>

app/views/account_types/show.html.erb
<h1>Account Type Details</h1>
<table>
<thead>
	<td> Account Title </td>
	<td> Amount </td>
</thead>
<tbody>
<% @accounts.each do |account| %>
<% if account.account_type.name == @accounttype.name %>
<tr>	
	<td><%= link_to "#{account.name}", account_path(account) %></td>
	<td><%= account.amount %></td> 
</tr>
<% end %>
<% end %>
</tbody>
</table>
<br>
<%= link_to "Return to Account Type main page", account_types_path%>
<br>
<%= link_to "Go to Transactions Home Page", transactions_path%>