config/routes.rb
OstazIii::Application.routes.draw do
  
  
  root 'transactions#index'
  devise_for :users
  resources :transactions
  resources :accounts
  resources :account_types

end

app/controllers/transactions_controller.rb
  class TransactionsController < ApplicationController
  #before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    #if params[:id].empty? == false
    #  @transaction = Transaction.find(params[:id])
    #else
    #  @transaction = Transaction.all
    #end
    @transaction = Transaction.find(params[:id])
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @accounts = Account.all
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
    @accounts = Account.all
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @account = Account.new
    @accounts = Account.all
    @transaction = Transaction.new()
    @transaction.id = params[:transaction][:id]
    @transaction.from_account_id = params[:transaction][:from_account_id][0].to_i
    @transaction.to_account_id = params[:transaction][:to_account_id][0].to_i
    @transaction.amount = params[:transaction][:amount]
    respond_to do |format|
      if @transaction.valid? #&& @transaction.errors.empty? == false
        @transaction.from_account.amount = @transaction.from_account.amount - @transaction.amount
        @transaction.from_account.save
        @transaction.to_account.amount = @transaction.to_account.amount + @transaction.amount
        @transaction.to_account.save
        @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transaction }
      else
        format.html { render action: 'new' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])
    @transaction.from_account_id = params[:transaction][:from_account_id][0].to_i
    @transaction.to_account_id = params[:transaction][:to_account_id][0].to_i
    @transaction.amount = params[:transaction][:amount]
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    unless @transaction.from_account_id == 3 || @transaction.from_account_id == 4
      @transaction.from_account.amount = @transaction.from_account.amount + @transaction.amount
      @transaction.from_account.save
    else
      @transaction.from_account.amount = @transaction.from_account.amount - @transaction.amount
      @transaction.from_account.save
    end
    unless @transaction.to_account_id == 3
      @transaction.to_account.amount = @transaction.to_account.amount - @transaction.amount
      @transaction.to_account.save
    else
      @transaction.to_account.amount = @transaction.to_account.amount + @transaction.amount
      @transaction.to_account.save
    end
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:from, :to, :amount)
    end
  end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
<% if @transaction.errors.empty? == false%>
<div id="error_explanation">
  <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

  <ul>
    <% @transaction.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :from_account_id %><%= f.select :from_account_id, @accounts.map{|x| x.id.to_s+" - "+x.name} %><br>

</div>
<div class="field">
  <%= f.label :to_account_id %><%= f.select :to_account_id, @accounts.map{|x| x.id.to_s+" - "+x.name} %><br>

</div>
<div class="field">
  <%= f.label :amount %><br>
  <%= f.text_field :amount %>
</div>
<div class="actions">

  <%= f.submit %>
</div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <thead>
    <tr>
      <th>from</th>
      <th>to</th>
      <th>amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= link_to "#{transaction.from_account.name}", account_path(transaction.from_account_id) %></td>
        <td><%= link_to "#{transaction.to_account.name}", account_path(transaction.to_account_id) %></td>
        <td><%= transaction.amount %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>
<br>
<%= link_to 'View Accounts', accounts_path%>
<br>
<%= link_to 'Add new Accounts', new_account_path%>
<br>
<%= link_to 'View Existing Account Types', account_types_path%>
<br>
<%= link_to 'Create a new Account Type', new_account_type_path%>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @transaction.from_account.name %>
</p>

<p>
  <strong>To:</strong>
  <%= @transaction.to_account.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>